name: Android CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type"
        required: true
        default: debug
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK (Debug or Release)
        run: |
          if [ "${{ github.event.inputs.buildType }}" == "release" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.buildType }}-apk
          path: app/build/outputs/apk/${{ github.event.inputs.buildType }}/*.apk
